### ISSUE TITLE
It's not working for me in post.ejs. When I try to put it in partial/page-full.ejs (Clean Blog Theme) it doesn't show up, either.

### ISSUE THREAD

**Issue by jordancclive** [ierhyna/hexo-reading-time#1]
Is that communicated clearly enough?

**Comment by ierhyna** [comment]
Hi @jordancclive ,

I have just tested the plugin with Clean Blog Theme, and it works for me.
There was no `partial/page-full.ejs` file in the theme's folder, so I put the code into `partial/article-full.ejs` file in line 24 after date and author info and it works:
```
<span class="meta">
  <!-- Date and Author -->
  ...
</span>
<%- readingTime(page.content) %>
```

Please let me know if you still have the issue.
