### ISSUE TITLE
Error loading plugin with Swig.

### ISSUE THREAD

**Issue by ivan-nginx** [ierhyna/hexo-reading-time#3]
Before edit template, `hexo clean && hexo g` give this error:
```
/var/www/vhosts/_hexo/node_modules/hexo-reading-time/lib/readingtime.js:4
module.exports = function(content, prefix = 'min. read') {
                                          ^
ERROR Plugin load failed: hexo-reading-time
SyntaxError: Unexpected token =
```

**Comment by ierhyna** [comment]
Hi, @ivan-nginx,
What version of NodeJS do you use?

**Comment by ivan-nginx** [comment]
```
hexo --version
hexo: 3.2.0
hexo-cli: 1.0.2
os: Linux 2.6.32-642.4.2.el6.x86_64 linux x64
http_parser: 1.2
node: 0.10.46
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.34
zlib: 1.2.3
modules: 11
openssl: 1.0.1e-fips
```
Last version, i think.

There is defined var in function:
(content, prefix = 'min. read')
And if remove ` = 'min. read'` — plugin then work, but without standart formatting.

**Comment by ierhyna** [comment]
As I see, you use the node version 0.10.46, while the latest stable LTS is 6.9.1: https://nodejs.org/en/

Version 0.10 is no longer supported: https://github.com/nodejs/LTS#lts-schedule

Please update node to v. 6.9.1, and try to run hexo again.

Thanks

**Comment by ivan-nginx** [comment]
Wow! How quickly node is growing...
Ok, but anyway, with hexo for now all of the most plugins are work, and hexo work too.
So, can u fix & adapted this plugin under old (0.x) versions of Node?
Thanks.

**Comment by ierhyna** [comment]
@ivan-nginx, I've just uploaded new version with the fix, please update hexo-reading-time plugin to the version 1.0.2.

However, I still highly recommend you to update NodeJS to 6.9.1, because versions 0.xx are no longer supported.

**Comment by ivan-nginx** [comment]
Ир, версии 0.xx поддерживаются до декабря 2016 года. А на данный момент 17-ое число.
Ну даже предположим, что сейчас уже Январь. В репозиториях CentOS до сих пор не обновлен node до последней этой версии.
Более того, неизвестно, как будут вести себя разработчики hexo. Быть может, они пока не особо собираются переходить на новые версии нода. А может быть и перейдут. Кто знает этих китайцев, да? Как с газопроводом...
Повторюсь: большинство текущих плагинов, конкретно под hexo, работают на старой ноде. Твой плагин, выходит, работает только под текущую стабильную. Обычно разработчики делают условия в плагинах под работу под старые версии (а через пол года-год эти условия убирают), вне зависимости от того, актуальна ли версия нода (движка) на данный момент или нет.
И последний такой некий аргумент: глянь на плагин hexo-wordcount: он работает на моей, старой версии node. Видимо, как будет новая версия нода — так он и свою обновит. Элементарные вещи же.

And thanks for update! ;)

**Comment by ierhyna** [comment]
Я уже сделала, чтобы плагин работал под 0.xx, и выгрузила в npm. Все должно заработать (замени пожалуйста в package.json версию плагина на 1.0.2 и сделай `npm install`).

Тут дело было в том, что я использовала объявление аргументов функции по-умолчанию, которое появилось в ES6, а это стандарт, который появился в ноде с 6 версии.

При этом, если что-то работало в версии 0.10, то оно будет работать и в версии 4x, и 6x. Поэтому в этом плане, с обновлениями проблем нет.

**Comment by ivan-nginx** [comment]
Да я понял, что обновление уже сделала.

> При этом, если что-то работало в версии 0.10, то оно будет работать и в версии 4x, и 6x. Поэтому в этом плане, с обновлениями проблем нет.

Так вот про что я и говорю) надо делать правильно, чётко. И всегда стараться учитывать синтаксис именно под старые версии чего бы то ни было (с пхп таких же историй полно).

P.S. May be closed.

**Comment by ierhyna** [comment]
Не соглашусь) Для того, чтобы JS и нода развивались, надо использовать современные стандарты.
