### ISSUE TITLE
Error time limit proportions.

### ISSUE THREAD

**Issue by ivan-nginx** [ierhyna/hexo-reading-time#4]
Например, запись с 4к словами. Плагин отображает, что чтение в 1 минуту можно. Как так то?)
P.S. Другой плагин (hexo-wordcount) говорит, что 25 минут.

Может стоит добавить какую-то опцию на установление скорости чтения?

**Comment by ierhyna** [comment]
Отличная идея! Буду рада пулл-реквесту.

**Comment by ierhyna** [comment]
Fixed with #6
